<?php
$api = file_get_contents("http://localhost:8080/api/item");
$dadosApi = json_decode($api);

// Verificar se os dados foram carregados corretamente
foreach ($dadosApi as $produto) {
}
?>


<section id="main_admin">
    <h2>ÁREA DO ADMISTRADOR</h2>
    <div class="conteiner_admin d-flex">

        <a class="conteiner_link" type="button" data-bs-toggle="modal" data-bs-target="#exampleModalProduto">
            <p>Produtos</p>
            <div class="logo">
                <i class="bi bi-archive-fill"></i>
            </div>
        </a>

        <!-- Modal -->
        <div class="modal fade  " id="exampleModalProduto" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="statiBackdropLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="header">
                        <h2 class="modal-title" id="exampleModalLabel">Produtos</h2>
                        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close"><i class="bi bi-x"></i></button>
                    </div>
                    <div class="modal-body">







                    <?php foreach ($dadosApi as $produto): ?>
                <?php 
                    // Calcular o valor da parcela em 10x
                    $parcela = $produto->preco / 10; 
                    ?>


                        <div class="conteiner_produto">

                            <div class="imagem">
                                <img src="<?= htmlspecialchars($produto->foto) ?>" alt="<?= htmlspecialchars($produto->nome) ?>">
                            </div>
                            <div class="descricao">
                                <p class="desc"><?= htmlspecialchars($produto->nome) ?></p>

                                <p class="preco">R$ <?= number_format($produto->preco, 2, ',', '.') ?></p>

                                <div class="auter">
                                    <a href="detalheProduto/<?= htmlspecialchars($produto->id_item) ?>">Ver anuncio</a>
                                    <div class="dropdown">
                                        <a class="dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-pen-fill"></i></a>
                                        <div class="dropdown-menu">
                                            <h3>Alterar produto</h3>
                                            <form method="POST" action="paginas/item/post_item.php">
                                                <span class="preco">Titulo</span>
                                                <textarea rows="" cols="" name="nome" placeholder="Novo titulo do produto"><?= htmlspecialchars($produto->nome) ?></textarea>
                                                <span class="preco">Descricao</span>
                                                <textarea rows="" cols="" name="descricao" placeholder="Nova descricao do produto"><?= htmlspecialchars($produto->descricao) ?></textarea>
                                                <span class="preco">Preço</span>
                                                <textarea rows="" cols="" name="preco" placeholder="Novo preco do produto"><?= htmlspecialchars($produto->preco) ?></textarea>
                                                <span class="preco">Estoque</span>
                                                <textarea rows="" cols="" name="estoque" placeholder="Novo estoque do produto"><?= htmlspecialchars($produto->estoque) ?></textarea>
                                                <span class="preco">Atributo 1</span>
                                                <textarea rows="" cols="" name="atributo_1" placeholder="Novo atributo 1 do produto"><?= htmlspecialchars($produto->atributo_1) ?></textarea>
                                                <span class="preco">Atributo 2</span>
                                                <textarea rows="" cols="" name="atributo_2" placeholder="Novo atributo 2 do produto"><?= htmlspecialchars($produto->atributo_2) ?></textarea>
                                                <span class="preco">Atributo 3</span>
                                                <textarea rows="" cols="" name="atributo_3" placeholder="Novo atributo 3 do produto"><?= htmlspecialchars($produto->atributo_3) ?></textarea>
                                                <span class="preco">Atributo 4</span>
                                                <textarea rows="" cols="" name="atributo_4" placeholder="Novo atributo 4 do produto"><?= htmlspecialchars($produto->atributo_4) ?></textarea>
                                                <span class="preco">Atributo 5</span>
                                                <textarea rows="" cols="" name="atributo_5" placeholder="Novo atributo 5 do produto"><?= htmlspecialchars($produto->atributo_5) ?></textarea>
                                                <span class="preco">Atributo 6</span>
                                                <textarea rows="" cols="" name="atributo_6" placeholder="Novo atributo 6 do produto"><?= htmlspecialchars($produto->atributo_6) ?></textarea>
                                                <div class="pbtn">
                                                    <button type="submit">Alterar</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <?php endforeach; ?>


                    </div>
                </div>
            </div>
        </div>

        <a class="conteiner_link"  type="button" data-bs-toggle="modal" data-bs-target="#exampleModalAdcionar">
            <p>Adicionar Produto</p>
            <div class="logo">
                <i class="bi bi-people-fill"></i>
            </div>
        </a>

        <!-- Modal -->
        <div class="modal fade " id="exampleModalAdcionar" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="statiBackdropLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="header">
                        <h2 class="modal-title" id="exampleModalLabel">Adicionar </h2>
                        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close"><i class="bi bi-x"></i></button>
                    </div>
                    <div class="modal-body">
                        <form action="">
                            <input type="" placeholder="Caminho da Imagem" required>
                            <input type="number" placeholder="Valor Produto" required>
                            <input type="text" placeholder="Categoria" required>
                            <textarea name="" id="" placeholder="Descricao do produto" required></textarea>

                            <div class="p_btn">
                                <button>Adicionar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <a class="conteiner_link" type="button" data-bs-toggle="modal" data-bs-target="#exampleModalRemover">
            <p>Remover Produtos</p>
            <div class="logo">
                <i class="bi bi-trash"></i>
            </div>
        </a>

        <!-- Modal -->
        <div class="modal fade  " id="exampleModalRemover" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="statiBackdropLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="header">
                        <h2 class="modal-title" id="exampleModalLabel">Remover</h2>
                        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close"><i class="bi bi-x"></i></button>
                    </div>
                    <div class="modal-body">
                        <div class="conteiner_produto">

                            <div class="imagem">
                                <img src="imagens/produtos/galaxyBuds.png" alt="">
                            </div>
                            <div class="descricao">
                                <p class="desc">Galaxy buds 3 pro, um fone muito top da famosa samsung um fone o galaxy AI
                                </p>

                                <p class="preco">R$ 1.600,00</p>

                                <div class="remover">
                                    <button id="aviso">Remover Produto</button>
                                </div>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>

        <a href="pedidos" class="conteiner_link">
            <p>Peditos</p>
            <div class="logo">
                <i class="bi bi-cart-fill"></i>
            </div>
        </a>



    </div>
</section>

<?php if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    if (isset($_POST['confirmar'])) {
        echo "<script>alert('Que Pena espero que Volte a Vender com Agente!');</script>";
    } else {
        echo "<script>alert('Muito obrigado por continuar com agente!');</script>";
    }
} ?>