<section id="area_login">
    <div class="conteiner_login">

        <h2>CRIE SUA CONTAR TECNOLO</h2>


        <form id="form" action="home" method="post" class="form">

                <input type="email" class="required" name="email" id="email" oninput="emailValidate()" placeholder="E-mail" required>
                <span class="span-required" style="margin:5px 0 0 10px; color:red; display: none;">E-mail inválido</span>

                <input type="password" name="Number" class="required" oninput="mainPasswordValidate()" required id="senha" placeholder="Senha" style="margin-top:20px;">
                <span class="span-required" style="display: none; color: red;">Deve ter pelo menos 8 digetos </span>

                <input type="password" placeholder="Confirmar Senha" name="Number" class="required" oninput="mainPasswordValidate2()" required id="senha" style="margin-top:20px;">
                <span class="span-required" style="display: none; color: red;">Senha senha incorreta</span>

                <input type="nome" name="nome" id="nome" class="required" oninput="nomeValidate()" placeholder="Nome Completo" style="margin-top:20px;" required>
                <span class="span-required" style="margin:5px 0 0 10px; color:red; display: none;">O nome deve ter pelo menos 3 digitos</span>

            <p style="margin-top:20px;">Data de Nascimento</p>

            <div class="conteiner_data">

                <input type="date" id="nascimento" style="width: 60%;" required>

            </div>

            <div class="btn_login">
                <a id="link" href="index.php">Voltar</a>
                <button type="submit" id="link">Confirmar</button>
            </div>
        </form>

        <a href="login">Entrar em uma conta Existente</a>
    </div>

    <div class="login_2" style="margin-bottom: 16px;">
        <a href=""><i class="bi bi-google"></i>Google</a>
        <a href=""><i class="bi bi-facebook"></i>Facebook</a>
    </div>

    <div class="check">

        <label for="termos"> <input type="checkbox" id="termos" name="termos"> Quero receber ofertas e novidades por e-mail, SMS, WhatsApp.</label>
        <label for="termos"> <input type="checkbox" id="termos" name="termos"> Li e estou de acordo com as <a href="">políticas da empresa e políticas de privacidade.</a></label>

    </div>

</section>

<div class="card">
    <img src="..." class="card-img-top" alt="...">

    <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
    </div>
</div>

<div class="card" aria-hidden="true">
    <img src="..." class="card-img-top" alt="...">
    <div class="card-body">
        <h5 class="card-title placeholder-glow">
            <span class="placeholder col-6"></span>
        </h5>
        <p class="card-text placeholder-glow">
            <span class="placeholder col-7"></span>
            <span class="placeholder col-4"></span>
            <span class="placeholder col-4"></span>
            <span class="placeholder col-6"></span>
            <span class="placeholder col-8"></span>
        </p>
        <a class="btn btn-primary disabled placeholder col-6" aria-disabled="true"></a>
    </div>
</div>