<section id="area_login">
    <div class="conteiner_login">

        <h2>CRIE SUA CONTAR TECNOLO</h2>

        <form id="form" action="login" method="post" class="form">

            <input type="email" class="required" id="email" oninput="emailValidate()" placeholder="E-mail" style="margin-bottom: 20px;" required>

            <input type="password" placeholder="Senha" style="margin-bottom: 20px;" required>
            <input type="password" placeholder="Confirmar Senha" style="margin-bottom: 20px;" required>
            <input type="nome" placeholder="Nome Completo" style="margin-bottom: 20px;" required>

            <p>Data de Nascimento</p>


            <div class="conteiner_data">

                <input type="date" id="nascimento" style="width: 60%;" required>

            </div>

            <div class="btn_login">
                <a id="link" href="index.php">Voltar</a>
                <button type="submit" id="link">Confirmar</button>
            </div>
        </form>

        <a href="login">Entrar em uma conta Existente</a>
    </div>

    <div class="login_2" style="margin-bottom: 16px;">
        <a href=""><i class="bi bi-google"></i>Google</a>
        <a href=""><i class="bi bi-facebook"></i>Facebook</a>
    </div>

    <div class="check">

        <label for="termos"> <input type="checkbox" id="termos" name="termos"> Quero receber ofertas e novidades por e-mail, SMS, WhatsApp.</label>
        <label for="termos"> <input type="checkbox" id="termos" name="termos"> Li e estou de acordo com as <a href="">políticas da empresa e políticas de privacidade.</a></label>

    </div>

</section>

<div class="card">
    <img src="..." class="card-img-top" alt="...">

    <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
    </div>
</div>

<div class="card" aria-hidden="true">
    <img src="..." class="card-img-top" alt="...">
    <div class="card-body">
        <h5 class="card-title placeholder-glow">
            <span class="placeholder col-6"></span>
        </h5>
        <p class="card-text placeholder-glow">
            <span class="placeholder col-7"></span>
            <span class="placeholder col-4"></span>
            <span class="placeholder col-4"></span>
            <span class="placeholder col-6"></span>
            <span class="placeholder col-8"></span>
        </p>
        <a class="btn btn-primary disabled placeholder col-6" aria-disabled="true"></a>
    </div>
</div>