<section id="area_cartao">
    <div class="conteiner_cartao" style="overflow: hidden !important;">

        <h2>CARTÃO DE CREDITO</h2>

        <form action="home" method="post" class="form"  id="formCartao" onsubmit="finalizarCompra(event)">

            <input type="text" name="numero" placeholder="Número do Cartão" required maxlength="16" inputmode="numeric">
            <input type="text" name="nome" placeholder="Nome Completo" required>
            <div class="validacao">
                <input type="month" name="validade" id="termos" required placeholder="Data de Validade">
                <input type="text" name="segurança" placeholder="Código de Segurança" maxlength="3" inputmode="numeric">
            </div>
            <input type="text" name="cpf" placeholder="CPF" required maxlength="11" inputmode="numeric">
            <div class="btn_login">
                <a id="link" href="index.php">Voltar</a>
                <button id="link" type="submit">Confirmar</button>
            </div>
        </form>
    </div>
</section>



<script src="JS/catao.js"></script>