<section id="area_endereco">

    <div class="conteiner_endereco">

        <h2>ADICIONER UM ENDERECO</h2>
        <form action="home" method="post" id="">

            <input type="nome" name="nome" placeholder="Nome Completo" class="required" id="nome" oninput="nomeEnderecoValidate">
            <span class="span-required" style="margin:5px 0 0 10px; color:red; display: none;">O nome deve ter pelo menos 3 digitos</span>

            <input class="input_cep" type="text" name="cep" placeholder="Insira seu CEP">

            <div class="cidade">

                <input type="text" name="estado" placeholder="Estado">
                <input type="text" name="cidade" placeholder="Cidade">

            </div>

            <input class="input_cep" type="text" name="bairro" placeholder="Bairro">

            <div class="rua">

                <input type="text" name="Rua/Avenida" placeholder="Rua/Avenida">
                <input type="text" name="numero" placeholder="Número">

            </div>

            <input type="tel" name="telefone" placeholder="Número de contato">


            <div class="btn">
                <button>Confirmar</button>
            </div>

        </form>
    </div>
</section>