<section id="area_login">
    <div class="conteiner_login">

        <h2>ESQUECEU SUA SENHA?</h2>

        <form method="POST" class="form" id="form">

    <input type="email" id="email" class="required" oninput="emailValidate()" name="email" placeholder="E-mail" required>
    <span class="span-required" style="margin:5px 0 0 10px; color:red; display: none;">E-mail inválido</span>
    <input type="text" name="nome" placeholder="Nome Completo" style="margin: 20px 0 0 0;" required>

    <div class="btn_login">
        <a href="login" id="link">Voltar</a>
        <button type="submit" id="link">Confirmar</button>
    </div>
</form>

        <a href="login">Entrar em uma conta Existente</a>
    </div>
</section>

<script src="paginas/validacoes/senha/port_senha.js"></script> 