<section id="area_login">
    <div class="conteiner_login">

        <h2>ESQUECEU SUA SENHA?</h2>

        <form action="redefinirSenha" method="post" class="form" id="form">

            <input type="email" class="required" name="email" id="email" oninput="emailValidate()" placeholder="E-mail" required>
            <span class="span-required" style="margin:5px 0 0 10px; color:red; display: none;">E-mail inválido</span>

            <input type="Name" placeholder="Nome Completo" style="margin: 20px 0 0 0;" required>

            <div class="btn_login">
                <a id="link" href="login">Voltar</a>
                <button id="link" type="submit">Confirmar</button>
            </div>
        </form>

        <a href="login">Entrar em uma conta Existente</a>
    </div>

    
</section>