<div id="carouselExampleIndicators" class="carousel slide " data-aos="fade" data-aos-duration="500">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
            aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
            aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
            aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active" data-bs-interval="4000">
            <img src="imagens/banner/bannerBuds.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item" data-bs-interval="4000">
            <img src="imagens/banner/banners24.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item" data-bs-interval="4000">
            <img src="imagens/banner/banner3.png" class="d-block w-100" alt="...">
        </div>
    </div>
    <button id="botao_carrosel" class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
        data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button id="botao_carrosel" class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
        data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
<section id="main_home">

    <div class="conteiner_carrosel">
        <div class="categoria">
            <h2>MAIS VENDIDOS</h2>

            <a href="maisvendidos">
                <p>Ver Todos</p>
            </a>

        </div>

        <hr>

        <div class="carousel" data-flickity='{ "wrapAround": true }'>

            <div class="carousel-cell">

                <a href="detalheProduto">
                    <div class="img"><img src="imagens/produtos/0_AEMYWY3BEAPTA_PRD_1500_1 2.png" alt></div>

                    <div class="descricao">
                        <p class="desc">iPhone 16 Pro Max Apple 512GB, Câmera
                            Tripla de 48MP, Tela 6,9 , Titânio Natural
                        </p>

                        <p class="preco">R$ 78.000,00</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$7.800,00</span></p>

                    </div>
                </a>

            </div>

            <div class="carousel-cell">

                <a href="">
                    <div class="img"><img src="imagens/produtos/s24ultra.png" alt></div>

                    <div class="descricao">
                        <p class="desc">Smartphone Samsung Galaxy S24 Ultra, Galaxy AI, Selfie de 12MP, Tela de 6.8" 1-120Hz, 256GB, 12GB RAM - Titânio Cinza
                        </p>

                        <p class="preco">R$ 104.500,99</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$10.450,99</span></p>

                    </div>
                </a>

            </div>

            <div class="carousel-cell">

                <a href>
                    <div class="img"><img src="imagens/produtos/galaxyBuds.png" alt></div>

                    <div class="descricao">
                        <p class="desc">Samsung Galaxy Buds3, Fone de Ouvido sem fio, som mais imersivo, Cancelamento Ativo de Ruído, Áudio Hi-Fi, Áudio 360, Tradução Simultanêa com Galaxy AI
                        </p>

                        <p class="preco">R$ 78.000,00</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$7.800,00</span></p>

                    </div>
                </a>

            </div>

            <div class="carousel-cell">

                <a href="">
                    <div class="img"><img src="imagens/produtos/galaxyzfold6.png" alt></div>

                    <div class="descricao">
                        <p class="desc">Smartphone Samsung Galaxy S24 Ultra, Galaxy AI, Selfie de 12MP, Tela de 6.8" 1-120Hz, 256GB, 12GB RAM - Titânio Cinza
                        </p>

                        <p class="preco">R$ 104.500,99</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$10.450,99</span></p>

                    </div>
                </a>

            </div>

            <div class="carousel-cell">

                <a href>
                    <div class="img"><img src="imagens/produtos/galaxyzfold6Cinza.png" alt></div>

                    <div class="descricao">
                        <p class="desc">Samsung Galaxy Buds3, Fone de Ouvido sem fio, som mais imersivo, Cancelamento Ativo de Ruído, Áudio Hi-Fi, Áudio 360, Tradução Simultanêa com Galaxy AI
                        </p>

                        <p class="preco">R$ 78.000,00</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$7.800,00</span></p>

                    </div>
                </a>

            </div>

            <div class="carousel-cell">

                <a href="">
                    <div class="img"><img src="imagens/produtos/galaxym55.png" alt></div>

                    <div class="descricao">
                        <p class="desc">Smartphone Samsung Galaxy S24 Ultra, Galaxy AI, Selfie de 12MP, Tela de 6.8" 1-120Hz, 256GB, 12GB RAM - Titânio Cinza
                        </p>

                        <p class="preco">R$ 104.500,99</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$10.450,99</span></p>

                    </div>
                </a>

            </div>


        </div>

    </div>

    <div class="conteiner_carrosel">
        <div class="categoria">
            <h2>LANÇAMENTOS</h2>

            <a href>
                <p>Ver Todos</p>
            </a>

        </div>

        <hr>

        <div class="carousel" data-flickity='{ "wrapAround": true }'>

            <div class="carousel-cell">

                <a href>
                    <div class="img"><img src="imagens/0_AEMYWY3BEAPTA_PRD_1500_1 2.png" alt></div>

                    <div class="descricao">
                        <p class="desc">iPhone 16 Pro Max Apple 512GB, Câmera
                            Tripla de 48MP, Tela 6,9 , Titânio Natural
                        </p>

                        <p class="preco">R$ 78.000,00</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$7.800,00</span></p>

                    </div>
                </a>

            </div>
            <div class="carousel-cell">

                <a href>
                    <div class="img"><img src="imagens/0_AEMYWY3BEAPTA_PRD_1500_1 2.png" alt></div>

                    <div class="descricao">
                        <p class="desc">iPhone 16 Pro Max Apple 512GB, Câmera
                            Tripla de 48MP, Tela 6,9", Titânio Natural
                        </p>

                        <p class="preco">R$ 78.000,00</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$7.800,00</span></p>

                    </div>
                </a>

            </div>
            <div class="carousel-cell">

                <a href>
                    <div class="img"><img src="imagens/0_AEMYWY3BEAPTA_PRD_1500_1 2.png" alt></div>

                    <div class="descricao">
                        <p class="desc">iPhone 16 Pro Max Apple 512GB, Câmera
                            Tripla de 48MP, Tela 6,9", Titânio Natural
                        </p>

                        <p class="preco">R$ 78.000,00</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$7.800,00</span></p>

                    </div>
                </a>

            </div>
            <div class="carousel-cell">

                <a href>
                    <div class="img"><img src="imagens/0_AEMYWY3BEAPTA_PRD_1500_1 2.png" alt></div>

                    <div class="descricao">
                        <p class="desc">iPhone 16 Pro Max Apple 512GB, Câmera
                            Tripla de 48MP, Tela 6,9", Titânio Natural
                        </p>

                        <p class="preco">R$ 78.000,00</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$7.800,00</span></p>

                    </div>
                </a>

            </div>
            <div class="carousel-cell">

                <a href>
                    <div class="img"><img src="imagens/0_AEMYWY3BEAPTA_PRD_1500_1 2.png" alt></div>

                    <div class="descricao">
                        <p class="desc">iPhone 16 Pro Max Apple 512GB, Câmera
                            Tripla de 48MP, Tela 6,9", Titânio Natural
                        </p>

                        <p class="preco">R$ 78.000,00</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$7.800,00</span></p>

                    </div>
                </a>

            </div>
            <div class="carousel-cell">

                <a href>
                    <div class="img"><img src="imagens/0_AEMYWY3BEAPTA_PRD_1500_1 2.png" alt></div>

                    <div class="descricao">
                        <p class="desc">iPhone 16 Pro Max Apple
                            512GB, Câmera Tripla de 48MP, Tela 6,9", Titânio
                            Natural
                        </p>

                        <p class="preco">R$ 78.000,00</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$7.800,00</span></p>

                    </div>
                </a>

            </div>

        </div>

    </div>

    <div class="banner" data-aos="fade" data-aos-duration="400">
        <img src="imagens/banner/banner6.jpg" alt="" width="100%" style="margin: 30px 0;">
    </div>

    <div class="conteiner_carrosel">
        <div class="categoria">
            <h2>EM PROMOÇÃO</h2>

            <a href>
                <p>Ver Todos</p>
            </a>

        </div>

        <hr>

        <div class="carousel" data-flickity='{ "wrapAround": true }'>

            <div class="carousel-cell">

                <a href>
                    <div class="img"><img src="imagens/0_AEMYWY3BEAPTA_PRD_1500_1 2.png" alt></div>

                    <div class="descricao">
                        <p class="desc">iPhone 16 Pro Max Apple 512GB, Câmera
                            Tripla de 48MP, Tela 6,9 , Titânio Natural
                        </p>

                        <p class="preco">R$ 78.000,00</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$7.800,00</span></p>

                    </div>
                </a>

            </div>
            <div class="carousel-cell">

                <a href>
                    <div class="img"><img src="imagens/0_AEMYWY3BEAPTA_PRD_1500_1 2.png" alt></div>

                    <div class="descricao">
                        <p class="desc">iPhone 16 Pro Max Apple 512GB, Câmera
                            Tripla de 48MP, Tela 6,9", Titânio Natural
                        </p>

                        <p class="preco">R$ 78.000,00</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$7.800,00</span></p>

                    </div>
                </a>

            </div>
            <div class="carousel-cell">

                <a href>
                    <div class="img"><img src="imagens/0_AEMYWY3BEAPTA_PRD_1500_1 2.png" alt></div>

                    <div class="descricao">
                        <p class="desc">iPhone 16 Pro Max Apple 512GB, Câmera
                            Tripla de 48MP, Tela 6,9", Titânio Natural
                        </p>

                        <p class="preco">R$ 78.000,00</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$7.800,00</span></p>

                    </div>
                </a>

            </div>
            <div class="carousel-cell">

                <a href>
                    <div class="img"><img src="imagens/0_AEMYWY3BEAPTA_PRD_1500_1 2.png" alt></div>

                    <div class="descricao">
                        <p class="desc">iPhone 16 Pro Max Apple 512GB, Câmera
                            Tripla de 48MP, Tela 6,9", Titânio Natural
                        </p>

                        <p class="preco">R$ 78.000,00</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$7.800,00</span></p>

                    </div>
                </a>

            </div>
            <div class="carousel-cell">

                <a href>
                    <div class="img"><img src="imagens/0_AEMYWY3BEAPTA_PRD_1500_1 2.png" alt></div>

                    <div class="descricao">
                        <p class="desc">iPhone 16 Pro Max Apple 512GB, Câmera
                            Tripla de 48MP, Tela 6,9", Titânio Natural
                        </p>

                        <p class="preco">R$ 78.000,00</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$7.800,00</span></p>

                    </div>
                </a>

            </div>
            <div class="carousel-cell">

                <a href>
                    <div class="img"><img src="imagens/0_AEMYWY3BEAPTA_PRD_1500_1 2.png" alt></div>

                    <div class="descricao">
                        <p class="desc">iPhone 16 Pro Max Apple
                            512GB, Câmera Tripla de 48MP, Tela 6,9", Titânio
                            Natural
                        </p>

                        <p class="preco">R$ 78.000,00</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$7.800,00</span></p>

                    </div>
                </a>

            </div>

        </div>

    </div>

    <div class="conteiner_carrosel">
        <div class="categoria">
            <h2>FRETE GRÁTIS</h2>

            <a href>
                <p>Ver Todos</p>
            </a>

        </div>

        <hr>

        <div class="carousel" data-flickity='{ "wrapAround": true }'>

            <div class="carousel-cell">

                <a href>
                    <div class="img"><img src="imagens/0_AEMYWY3BEAPTA_PRD_1500_1 2.png" alt></div>

                    <div class="descricao">
                        <p class="desc">iPhone 16 Pro Max Apple 512GB, Câmera
                            Tripla de 48MP, Tela 6,9 , Titânio Natural
                        </p>

                        <p class="preco">R$ 78.000,00</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$7.800,00</span></p>

                    </div>
                </a>

            </div>
            <div class="carousel-cell">

                <a href>
                    <div class="img"><img src="imagens/0_AEMYWY3BEAPTA_PRD_1500_1 2.png" alt></div>

                    <div class="descricao">
                        <p class="desc">iPhone 16 Pro Max Apple 512GB, Câmera
                            Tripla de 48MP, Tela 6,9", Titânio Natural
                        </p>

                        <p class="preco">R$ 78.000,00</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$7.800,00</span></p>

                    </div>
                </a>

            </div>
            <div class="carousel-cell">

                <a href>
                    <div class="img"><img src="imagens/0_AEMYWY3BEAPTA_PRD_1500_1 2.png" alt></div>

                    <div class="descricao">
                        <p class="desc">iPhone 16 Pro Max Apple 512GB, Câmera
                            Tripla de 48MP, Tela 6,9", Titânio Natural
                        </p>

                        <p class="preco">R$ 78.000,00</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$7.800,00</span></p>

                    </div>
                </a>

            </div>
            <div class="carousel-cell">

                <a href>
                    <div class="img"><img src="imagens/0_AEMYWY3BEAPTA_PRD_1500_1 2.png" alt></div>

                    <div class="descricao">
                        <p class="desc">iPhone 16 Pro Max Apple 512GB, Câmera
                            Tripla de 48MP, Tela 6,9", Titânio Natural
                        </p>

                        <p class="preco">R$ 78.000,00</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$7.800,00</span></p>

                    </div>
                </a>

            </div>
            <div class="carousel-cell">

                <a href>
                    <div class="img"><img src="imagens/0_AEMYWY3BEAPTA_PRD_1500_1 2.png" alt></div>

                    <div class="descricao">
                        <p class="desc">iPhone 16 Pro Max Apple 512GB, Câmera
                            Tripla de 48MP, Tela 6,9", Titânio Natural
                        </p>

                        <p class="preco">R$ 78.000,00</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$7.800,00</span></p>

                    </div>
                </a>

            </div>
            <div class="carousel-cell">

                <a href>
                    <div class="img"><img src="imagens/0_AEMYWY3BEAPTA_PRD_1500_1 2.png" alt></div>

                    <div class="descricao">
                        <p class="desc">iPhone 16 Pro Max Apple
                            512GB, Câmera Tripla de 48MP, Tela 6,9", Titânio
                            Natural
                        </p>

                        <p class="preco">R$ 78.000,00</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$7.800,00</span></p>

                    </div>
                </a>

            </div>

        </div>

    </div>


</section>