<section id="area_login">
    <div class="conteiner_login" style="overflow: hidden !important;">

        <h2>ENTRAR COM UMA CONTAR TECNOLO</h2>

        <form method="POST" action="home" class="form" id="formLogin">

            <input type="email" class="required" id="email" name="email" oninput="emailValidate()" placeholder="E-mail" required>
            <span class="span-required" style="margin:5px 0 0 10px; color:red; display: none;">E-mail inválido</span>

            <input type="password" class="required" id="senha" name="senha" oninput="mainPasswordValidate()" placeholder="Senha" style="margin: 20px 0 0 0;" required>
            <span class="span-required" style=" margin:5px 0 0 10px; display: none; color: red;">Senha muito CurtaMinimo 8 digitos </span>

            <a href="esqueciMinhaSenha" style="margin: 10px 0 0 15px;" class="senha">Esqueceu minha senha</a>

            <div class="btn_login">
                <a id="link" href="index.php">Voltar</a>
                <button id="link" type="submit">Confirmar</button>
            </div>
        </form>

        <a href="cadastro">Cadastrar-se</a>
    </div>

    <div class="login_2">
        <a href="login"><i class="bi bi-google"></i>Google</a>
        <a href="login"><i class="bi bi-facebook"></i>Facebook</a>
    </div>
</section>


<script src="paginas/validacoes/login/post_login.js"></script>