<section id="main_produtos">
    <h2>Mais Vendidos</h2>
    <hr>
    <div class="produto_flex">
        <a href="detalheProduto" class="conteiner_produto">

            <div class="imagem">
                <img src="imagens/0_AEMYWY3BEAPTA_PRD_1500_1 2.png" alt="" width="100%">
            </div>
            <div class="descricao">
                <p class="desc">iPhone 16 Pro Max Apple 512GB, Câmera
                    Tripla de 48MP, Tela 6,9 , Titânio Natural
                </p>

                <p class="preco">R$ 78.000,00</p>
                <p class="sub_preco">Aviste no Pix ou até <span>10x de
                        R$7.800,00</span></p>

            </div>

        </a>

        <a href="" class="conteiner_produto">

            <div class="imagem">
                <img src="imagens/0_AEMYWY3BEAPTA_PRD_1500_1 2.png" alt="" width="100%">
            </div>
            <div class="descricao">
                <p class="desc">iPhone 16 Pro Max Apple 512GB, Câmera
                    Tripla de 48MP, Tela 6,9 , Titânio Natural
                </p>

                <p class="preco">R$ 78.000,00</p>
                <p class="sub_preco">Aviste no Pix ou até <span>10x de
                        R$7.800,00</span></p>

            </div>

        </a>

        <a href="" class="conteiner_produto">

            <div class="imagem">
                <img src="imagens/0_AEMYWY3BEAPTA_PRD_1500_1 2.png" alt="" width="100%">
            </div>
            <div class="descricao">
                <p class="desc">iPhone 16 Pro Max Apple 512GB, Câmera
                    Tripla de 48MP, Tela 6,9 , Titânio Natural
                </p>

                <p class="preco">R$ 78.000,00</p>
                <p class="sub_preco">Aviste no Pix ou até <span>10x de
                        R$7.800,00</span></p>

            </div>

        </a>

        <a href="" class="conteiner_produto">

            <div class="imagem">
                <img src="imagens/0_AEMYWY3BEAPTA_PRD_1500_1 2.png" alt="" width="100%">
            </div>
            <div class="descricao">
                <p class="desc">iPhone 16 Pro Max Apple 512GB, Câmera
                    Tripla de 48MP, Tela 6,9 , Titânio Natural
                </p>

                <p class="preco">R$ 78.000,00</p>
                <p class="sub_preco">Aviste no Pix ou até <span>10x de
                        R$7.800,00</span></p>

            </div>

        </a>

        <a href="" class="conteiner_produto">

            <div class="imagem">
                <img src="imagens/0_AEMYWY3BEAPTA_PRD_1500_1 2.png" alt="" width="100%">
            </div>
            <div class="descricao">
                <p class="desc">iPhone 16 Pro Max Apple 512GB, Câmera
                    Tripla de 48MP, Tela 6,9 , Titânio Natural
                </p>

                <p class="preco">R$ 78.000,00</p>
                <p class="sub_preco">Aviste no Pix ou até <span>10x de
                        R$7.800,00</span></p>

            </div>

        </a>

    </div>
</section