<section id="main_detalhe">

    <div class="titulo">
        <h4>iPhone 16 Pro Max Apple 512GB, Câmera Tripla de 48MP, Tela 6,9", Titânio Natural. </h4>
        <p>Produto Disponivel</p>
        <hr>
    </div>

    <div class="conteiner_produto_flex">

        <div class="conteiner_produto">
            <img src="imagens/0_AEMYWY3BEAPTA_PRD_1500_1 2.png" alt>
        </div>

        <div class="conteiner_descricao">

            <div class="titulo2">
                <h4>iPhone 16 Pro Max Apple 512GB, Câmera Tripla de 48MP, Tela 6,9", Titânio Natural. </h4>
                <p>Produto Disponivel</p>
                <hr>
            </div>

            <div class="compra">
                <div class="conteiner_preco">
                    <p class="preco">R$ 78.000,00</p>
                    <p class="subPreco">Aviste no Pix ou até <span>10x de R$7.800,00</span> sem juros</p>
                </div>

                <form action="pagamento" class="compra_botao">
                    <button class="comprar_cart"><i class="bi bi-cart-plus"></i> COMPRAR</button>
                    <button class="carrinho"><i class="bi bi-cart-plus"></i></button>
                </form>
            </div>

            <hr>

            <div class="cep">
                <div class="busca">
                    <form action="">
                        <input type="text" placeholder="Insira o CEP" maxlength="8" inputmode="numeric">
                        <button>OK</button>
                    </form>
                </div>

                <a type="button" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    Não lembro meu CEP
                </a>

                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h2 class="modal-title" id="exampleModalLabel">Busque seu CEP</h2>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">

                                <form action="">
                                    <input type="text" placeholder="Estado">
                                    <input type="text" placeholder="Cidade">

                                    <span>
                                        <n>Seu CEP:</n> 87355-000
                                    </span>

                                    <div class="btn">
                                        <button>Buscar</button>
                                    </div>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <div class="descricao_completa">
                <p>iPhone 16 Pro Max. Com estrutura em titânio, Controle da Câmera, 4K Dolby Vision a 120 qps e o chip A18 Pro. Avisos legais *As telas têm bordas arredondadas. Quando medida como um retângulo, a tela tem 6,12 polegadas (iPhone 16), 6,69 polegadas (iPhone 16 Plus), 6,27 polegadas (iPhone 16 Pro) ou 6,86 polegadas (iPhone 16 Pro Max) na diagonal. A área real de visualização é menor.</p>
            </div>
        </div>

    </div>

    <div class="descricao_completa2">
        <H2>Descricão </H2>
        <p>iPhone 16 Pro Max. Com estrutura em titânio, Controle da Câmera, 4K Dolby Vision a 120 qps e o chip A18 Pro. Avisos legais *As telas têm bordas arredondadas. Quando medida como um retângulo, a tela tem 6,12 polegadas (iPhone 16), 6,69 polegadas (iPhone 16 Plus), 6,27 polegadas (iPhone 16 Pro) ou 6,86 polegadas (iPhone 16 Pro Max) na diagonal. A área real de visualização é menor.</p>
    </div>

    <div class="conteiner_ficha">

        <h2>Ficha Técnica</h2>

        <ul>
            <li>
                <p id="paragrafo">Marca: Apple</p>
            </li>
            <li>
                <p id="paragrafo">Modelo: iPhone 16 Pro Max</p>
            </li>
            <li>
                <p id="paragrafo">Cor: Títanio</p>
            </li>
            <li>
                <p id="paragrafo">Memorias: 512GB/8GB de Ram</p>
            </li>
            <li>
                <p id="paragrafo">Tela: Super Retina XDR OLED de 6.7 polegadas FHD+ (2560x1600)</p>
            </li>
        </ul>

    </div>

    <div id="conteiner_carrosel">
        <div class="categoria">
            <h2>MAIS VENDIDOS</h2>

            <a href="paginasProdutos/maisvendidosmeu ">
                <p>Ver Todos</p>
            </a>

        </div>

        <div class="carousel" data-flickity='{ "wrapAround": true }'>

            <div class="carousel-cell">

                <a href="detalheProduto">
                    <div class="img"><img src="imagens/produtos/0_AEMYWY3BEAPTA_PRD_1500_1 2.png" alt></div>

                    <div class="descricao">
                        <p class="desc">iPhone 16 Pro Max Apple 512GB, Câmera
                            Tripla de 48MP, Tela 6,9 , Titânio Natural
                        </p>

                        <p class="preco">R$ 78.000,00</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$7.800,00</span></p>

                    </div>
                </a>

            </div>

            <div class="carousel-cell">

                <a href="">
                    <div class="img"><img src="imagens/produtos/s24ultra.png" alt></div>

                    <div class="descricao">
                        <p class="desc">Smartphone Samsung Galaxy S24 Ultra, Galaxy AI, Selfie de 12MP, Tela de 6.8" 1-120Hz, 256GB, 12GB RAM - Titânio Cinza
                        </p>

                        <p class="preco">R$ 104.500,99</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$10.450,99</span></p>

                    </div>
                </a>

            </div>

            <div class="carousel-cell">

                <a href>
                    <div class="img"><img src="imagens/produtos/galaxyBuds.png" alt></div>

                    <div class="descricao">
                        <p class="desc">Samsung Galaxy Buds3, Fone de Ouvido sem fio, som mais imersivo, Cancelamento Ativo de Ruído, Áudio Hi-Fi, Áudio 360, Tradução Simultanêa com Galaxy AI
                        </p>

                        <p class="preco">R$ 78.000,00</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$7.800,00</span></p>

                    </div>
                </a>

            </div>

            <div class="carousel-cell">

                <a href="">
                    <div class="img"><img src="imagens/produtos/galaxyzfold6.png" alt></div>

                    <div class="descricao">
                        <p class="desc">Smartphone Samsung Galaxy S24 Ultra, Galaxy AI, Selfie de 12MP, Tela de 6.8" 1-120Hz, 256GB, 12GB RAM - Titânio Cinza
                        </p>

                        <p class="preco">R$ 104.500,99</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$10.450,99</span></p>

                    </div>
                </a>

            </div>

            <div class="carousel-cell">

                <a href>
                    <div class="img"><img src="imagens/produtos/galaxyzfold6Cinza.png" alt></div>

                    <div class="descricao">
                        <p class="desc">Samsung Galaxy Buds3, Fone de Ouvido sem fio, som mais imersivo, Cancelamento Ativo de Ruído, Áudio Hi-Fi, Áudio 360, Tradução Simultanêa com Galaxy AI
                        </p>

                        <p class="preco">R$ 78.000,00</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$7.800,00</span></p>

                    </div>
                </a>

            </div>

            <div class="carousel-cell">

                <a href="">
                    <div class="img"><img src="imagens/produtos/galaxym55.png" alt></div>

                    <div class="descricao">
                        <p class="desc">Smartphone Samsung Galaxy S24 Ultra, Galaxy AI, Selfie de 12MP, Tela de 6.8" 1-120Hz, 256GB, 12GB RAM - Titânio Cinza
                        </p>

                        <p class="preco">R$ 104.500,99</p>
                        <p class="sub_preco">Aviste no Pix ou até <span>10x de
                                R$10.450,99</span></p>

                    </div>
                </a>

            </div>


        </div>

    </div>

</section>

<!-- Negrito as primeiras palavras -->
<script>
    const paragraphs = document.querySelectorAll('#paragrafo');

    paragraphs.forEach(paragraph => {
        let text = paragraph.innerHTML;
        let words = text.split(' ');
        words[0] = '<strong>' + words[0] + '</strong>';
        paragraph.innerHTML = words.join(' ');
    });
</script>