<section id="main_produtos">

    <div class="top">
        <h2>SmartPhones</h2>
        <button class="btn-of" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling"><i class="bi bi-list"></i>Filtro</button>

        <div class="offcanvas offcanvas-start" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasScrolling" aria-labelledby="offcanvasScrollingLabel">
            <div class="header">
                <h5 class="offcanvas-title" id="offcanvasScrollingLabel">FILTRO</h5>
                <button type="button" class="close" data-bs-dismiss="offcanvas" aria-label="Close"><i class="bi bi-x"></i></button>

            </div>
            <hr>
            <div class="offcanvas-body">
                <form action="">
                    <h5>Valor</h5>
                    <ul>
                        <li><input type="checkbox" id="valor1"> <label for="valor1">R$ 500,00</label></li>
                        <li><input type="checkbox" id="valor2"> <label for="valor2">R$ 1000,00</label></li>
                        <li><input type="checkbox" id="valor3"> <label for="valor3">R$ 1200,00</label></li>
                        <li><input type="checkbox" id="valor4"> <label for="valor4">R$ 1500,00</label></li>
                        <li><input type="checkbox" id="valor5"> <label for="valor5">R$ 2000,00</label></li>
                        <li><input type="checkbox" id="valor6"> <label for="valor6">R$ 2400,00</label></li>
                    </ul>
                    <button class="filtrar">Filtrar Agora</button>
                </form>
            </div>
        </div>

    </div>


    <div class="produto_flex">
        <a href="detalheProduto" class="conteiner_produto">

            <div class="imagem">
                <img src="imagens/0_AEMYWY3BEAPTA_PRD_1500_1 2.png" alt="">
            </div>
            <div class="descricao">
                <p class="desc">iPhone 16 Pro Max Apple 512GB, Câmera
                    Tripla de 48MP, Tela 6,9 , Titânio Natural
                </p>

                <p class="preco">R$ 78.000,00</p>
                <p class="sub_preco">Aviste no Pix ou até <span>10x de
                        R$7.800,00</span></p>

            </div>

        </a>
        <a href="detalheProduto" class="conteiner_produto">

            <div class="imagem">
                <img src="imagens/produtos/s24ultra.png" alt="">
            </div>
            <div class="descricao">
                <p class="desc">iPhone 16 Pro Max Apple 512GB, Câmera
                    Tripla de 48MP, Tela 6,9 , Titânio Natural
                </p>

                <p class="preco">R$ 78.000,00</p>
                <p class="sub_preco">Aviste no Pix ou até <span>10x de
                        R$7.800,00</span></p>

            </div>

        </a>
        <a href="detalheProduto" class="conteiner_produto">

            <div class="imagem">
                <img src="imagens/produtos/galaxym55.png" alt="">
            </div>
            <div class="descricao">
                <p class="desc">iPhone 16 Pro Max Apple 512GB, Câmera
                    Tripla de 48MP, Tela 6,9 , Titânio Natural
                </p>

                <p class="preco">R$ 78.000,00</p>
                <p class="sub_preco">Aviste no Pix ou até <span>10x de
                        R$7.800,00</span></p>

            </div>

        </a>
        <a href="detalheProduto" class="conteiner_produto">

            <div class="imagem">
                <img src="imagens/produtos/galaxyzfold6.png" alt="">
            </div>
            <div class="descricao">
                <p class="desc">iPhone 16 Pro Max Apple 512GB, Câmera
                    Tripla de 48MP, Tela 6,9 , Titânio Natural
                </p>

                <p class="preco">R$ 78.000,00</p>
                <p class="sub_preco">Aviste no Pix ou até <span>10x de
                        R$7.800,00</span></p>

            </div>

        </a>
        <a href="detalheProduto" class="conteiner_produto">

            <div class="imagem">
                <img src="imagens/produtos/galaxya55.png" alt="">
            </div>
            <div class="descricao">
                <p class="desc">iPhone 16 Pro Max Apple 512GB, Câmera
                    Tripla de 48MP, Tela 6,9 , Titânio Natural
                </p>

                <p class="preco">R$ 78.000,00</p>
                <p class="sub_preco">Aviste no Pix ou até <span>10x de
                        R$7.800,00</span></p>

            </div>

        </a>
        <a href="detalheProduto" class="conteiner_produto">

            <div class="imagem">
                <img src="imagens/produtos/galaxyzfold6Cinza.png" alt="">
            </div>
            <div class="descricao">
                <p class="desc">iPhone 16 Pro Max Apple 512GB, Câmera
                    Tripla de 48MP, Tela 6,9 , Titânio Natural
                </p>

                <p class="preco">R$ 78.000,00</p>
                <p class="sub_preco">Aviste no Pix ou até <span>10x de
                        R$7.800,00</span></p>

            </div>

        </a>
    </div>
</section